### ISSUE TITLE
wheels are off in Rviz

### ISSUE THREAD

**Issue by cipy** [iRobotEducation/create3_sim#181] opened 2022-05-12 19:30 UTC
**Describe the bug**

wheels are "off" in RViz

<img width="267" alt="Screenshot 2022-05-12 at 22 28 29" src="https://user-images.githubusercontent.com/1131154/168153647-84057f25-2df3-498d-ac1a-bce4447f2425.png">

<img width="210" alt="Screenshot 2022-05-12 at 22 28 13" src="https://user-images.githubusercontent.com/1131154/168153642-da4f1c40-f59b-4abf-8132-408f3f17319a.png">

**To Reproduce**
1. Ubuntu 20.04 ARM64

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by alsora** [comment] 2022-05-13 10:59
Closing this issue as a duplicate of https://github.com/iRobotEducation/create3_sim/issues/125

This is a well known problem and it may be due to some bugs/errors in the dependencies of this application

**Closed by alsora** 2022-05-13 10:59 UTC
Labels: bug
