### ISSUE TITLE
Wheels does not show up on bringup in ignition and rviz

### ISSUE THREAD

**Issue by ipa-rar** [iRobotEducation/create3_sim#190] opened 2022-11-08 19:33 UTC
**Describe the bug**
The robot launches without wheels and there is no transform between base_link and its wheels.

**To Reproduce**

  -  OS:Ubuntu 20.04
   - ROS Distro: Galactic
   - Built from source `galactic` branch

1.``ros2 launch irobot_create_ignition_bringup create3_ignition.launch.py ``
2. The issues is found in [this](https://github.com/iRobotEducation/create3_sim/blob/main/irobot_create_common/irobot_create_description/urdf/wheel_with_wheeldrop.urdf.xacro) urdf file where the parent_link is not defined. 
3. Adding  ``<xacro:property name="parent_link" value="base_link" />`` solves the issue with the transform between wheels and base_link but the wheels does not appear in the simualtion.

**Expected behavior**
The robot should launch with wheels in ignition and show the transform between its wheels and base_link 

**Screenshots**
![Screenshot from 2022-11-08 14-50-03](https://user-images.githubusercontent.com/49311464/200657205-db9dd46e-8bb0-47f2-918a-c0414efc4575.png)

**Comment by alsora** [comment] 2022-11-08 22:17
Hi @ipa-rar,
I think that this issue is a duplicate of https://github.com/iRobotEducation/create3_sim/issues/125

From our previous analysis, this problem was due to the ros2_control dependency.
It looks like the underlying issue has not been fixed yet in Galactic.

**Closed by alsora** 2022-11-08 22:17 UTC
Labels: bug
